FROM alpine:latest

LABEL MAINTAINER="Fedorov"

# 替换apk使用的源
COPY repositories /etc/apk/repositories
COPY requirements.txt /tmp/requirements.txt

# 设定容器时间
RUN echo "export TZ='UTC'" > /etc/profile

# Install required packages and remove the apt packages cache when done.
RUN apk add python3 \
	python3-dev \
	gcc \
	g++ \
	mariadb-connector-c-dev \
	mariadb-dev \
	linux-headers \
	pcre-dev \
	musl-dev \
	libxml2-dev \
	libxslt-dev \
	nginx \
	jpeg-dev \
	zlib-dev \
	supervisor \
	py3-pip


RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# ENV PYTHONPATH=/workspaces/python:$PYTHONPATH
# 设置 HTTP 和 HTTPS 代理
# ENV HTTP_PROXY=http://10.165.27.210:7890
# ENV HTTPS_PROXY=http://10.165.27.210:7890
# ENV HTTP_PROXY=http://192.168.12.166:7890
# ENV HTTPS_PROXY=http://192.168.12.166:7890
# ENV NO_PROXY=localhost,127.0.0.1

EXPOSE 9999

CMD ["python"]